version: '3'
services:
  db_api:
    container_name: api_mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: 'userdb'
      MYSQL_PASSWORD: 'passdb'
      MYSQL_DATABASE: 'testedb'
  app_api:
    container_name: api_web
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    dns: 8.8.8.8
    command: bash -c "service apache2 start && cd /var/www/html && composer install && tail -f /dev/null"
    links:
      - 'db_api'
