version: '3'
services:
  db:
    container_name: web_mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "passdb"
      MYSQL_DATABASE: "testedb"
  web:
    container_name: web_app
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    dns: 8.8.8.8
    command: bash -c "service apache2 restart && 
      chmod -R 777 /var/www/html && 
      cd /var/www/html && 
      cp env.exemple .env && 
      composer install && 
      php artisan key:generate && 
      php artisan migrate:fresh --seed && 
      tail -f /dev/null"
    links:
      - db
    depends_on:
      - db
