version: '3'
services:
  database:
    container_name: teste_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_USER: 'userdb'
      MYSQL_PASSWORD: 'passdb'
      MYSQL_DATABASE: 'testedb'
  web:
    container_name: teste_api
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/app/
    ports:
      - 80:80
    dns: 8.8.8.8
    command: bash -c "apache2ctl -D FOREGROUND"
    links:
      - 'database'
